# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 'Publish - npm'
on:
  pull_request:
    types: [ closed ]

jobs:
  publish:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/publish-npm.yml@v1
    secrets: inherit
